copy into CREDIT_SCORE_PHASE2.PSI.chargebacks(REFERENCE_NUM,SUPPLIER_ID,CLIENT_NAME,ENTITY,TYPE, SUMMARY_ACCT,BILL_STATUS, NDG_ID, NDG_NAME,CUSTOMER_ID,CUSTOMER_TYPE_ID, CUSTOMER_TYPE, VENDOR, CUSTOMER_NAME, TOTAL_AMOUNT , OPEN_BALANCE , PAID_AMOUNT, BILL_DATE, CB_DUEDATE, PAID_DATE)
from (select
$2 as REFERENCE_NUM,
$3 as SUPPLIER_ID,
$4 as CLIENT_NAME,
$5 as ENTITY,
$6 as TYPE,
$7 as SUMMARY_ACCT,
$8 as BILL_STATUS,
$9 as NDG_ID,
$10 as NDG_NAME,
$11 as CUSTOMER_ID,
$12 as CUSTOMER_TYPE_ID,
$13 as CUSTOMER_TYPE,
$14 as VENDOR,
$15 as CUSTOMER_NAME,
$16 as TOTAL_AMOUNT,
$17 as OPEN_BALANCE,
$18 as PAID_AMOUNT,
$19 as BILL_DATE,
$20 as CB_DUEDATE,
$21 as PAID_DATE
FROM @CREDIT_SCORE_PHASE2.psi.S3_INTEGRATION/PHASE2/{{ execution_date.strftime('%Y/%m/%d') }}/Chargebacks.csv)
FILE_FORMAT = (FORMAT_NAME = 'CREDIT_SCORE_PHASE2.psi.S3_csv_to_snowflake');
